name: Reusable Capacitor Android Build

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      package_name:
        required: true
        type: string
      node_version:
        required: false
        type: string
        default: '18'
      java_version:
        required: false
        type: string
        default: '11'
      app_version:
        required: false
        type: string
        default: '1.0.0'
      build_command:
        required: false
        type: string
        default: 'npm run build'
      deploy_track:
        required: false
        type: string
        default: 'internal'
      capacitor_config_path:
        required: false
        type: string
        default: 'capacitor.config.ts'
      
    secrets:
      KEYSTORE_BASE64:
        required: true
      KEYSTORE_PASSWORD:
        required: true
      KEY_ALIAS:
        required: true
      KEY_PASSWORD:
        required: true
      SERVICE_ACCOUNT_JSON:
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout calling repository
      uses: actions/checkout@v4

    - name: Checkout pipeline repository
      uses: actions/checkout@v4
      with:
        repository: your-org/pwa-android-pipeline
        path: .pipeline
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'npm'

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java_version }}

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install dependencies
      run: npm ci

    - name: Build React app
      run: ${{ inputs.build_command }}

    - name: Update Capacitor config
      run: |
        chmod +x .pipeline/scripts/update-capacitor-config.sh
        .pipeline/scripts/update-capacitor-config.sh \
          "${{ inputs.package_name }}" \
          "${{ inputs.app_name }}" \
          "${{ inputs.app_version }}" \
          "${{ inputs.capacitor_config_path }}"

    - name: Sync Capacitor
      run: |
        npx cap sync android
        npx cap update android

    - name: Setup signing
      run: |
        chmod +x .pipeline/scripts/setup-capacitor-signing.sh
        .pipeline/scripts/setup-capacitor-signing.sh
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    - name: Build APK
      run: |
        cd android
        ./gradlew assembleRelease

    - name: Upload to Google Play
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        packageName: ${{ inputs.package_name }}
        releaseFiles: android/app/build/outputs/apk/release/app-release.apk
        track: ${{ inputs.deploy_track }}
        status: completed